### ISSUE TITLE
Adding classes to the whole list don't work in Reading mode

### ISSUE THREAD

**Issue by anareaty** [LilaRest/obsidian-custom-classes#2]
**Describe the bug**
Hello! It seams that adding classes to the whole list don't work in Reading mode (it works okay in Live Preview mode).

**To Reproduce**

Here is the source code I used:

```
`cls: red` 
- jgjhgjgjhgj
- fghfghfgh
- fghfghfgh`
```

I checked the html, in Live Preview it renders like this:

```
<div class="cc-container" contenteditable="false">
    <div class="markdown-rendered cc-renderer red">
        <ul>
            <li>jgjhgjgjhgj</li>
            <li>fghfghfgh</li>
            <li>fghfghfgh</li>
        </ul>
    </div>
</div>
```

But in Reading mode it renders like this:

```
<div>
    <p class="red">
        <code style="display: none;" cc-processed="true">cls: red</code> 
    </p>
</div>
<div>
    <ul class="has-list-bullet">
        <li data-line="0"><div class="list-bullet"></div>jgjhgjgjhgj</li>
        <li data-line="1"><div class="list-bullet"></div>fghfghfgh</li>
        <li data-line="2"><div class="list-bullet"></div>fghfghfgh</li>
    </ul>
</div>
```

So the class do not apply to the list itself.

**Comment by LilaRest** [comment]
Hi @anareaty, thanks for your contribution through this bug report !

I've been very astonished to see this one because, as a Read mode user, my _Custom Classes_ code blocks have always been rendered properly.

After some investigations I've been able to figure that the problem comes from the space that is put right after the _Custom Classes_ code block in your example :
```md
      this one
          |
          v
`cls: red` 
- jgjhgjgjhgj
- fghfghfgh
- fghfghfgh`
```

If I remove the space, all works well again.

I think this is caused by a wrong trimming process in my code, I'll fix that soon. Until that be careful to not add leading space after your _Custom Classes_ code blocks haha :smile:

**Comment by anareaty** [comment]
Oh, cool. I didn't notice there was a space here. Thanks for the figuring it out, I find the ability to create the class for the whole block the most useful, especially for columns and stuff like this.

**Comment by anareaty** [comment]
Oh, cool. I didn't notice there was a space here. Thanks for the figuring it out, I find the ability to create the class for the whole block the most useful, especially for columns and stuff like this.
